"""sync with current models

Revision ID: 0c80e817ee1d
Revises: 
Create Date: 2026-01-07 15:53:26.298895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c80e817ee1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_action_logs')
    op.create_foreign_key(None, 'event_plans', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'feedbacks', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'point_logs', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'recipe_versions', 'user', ['submitted_by'], ['user_id'])
    op.create_foreign_key(None, 'recipes', 'user', ['created_by'], ['user_id'])
    op.create_foreign_key(None, 'sessions', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'token_transactions', 'user', ['user_id'], ['user_id'])
    op.drop_column('user', 'total_points')
    # Remove 'validator' role if exists, add 'user', 'trainer', 'admin' roles if not present
    from sqlalchemy.sql import table, column
    from sqlalchemy import String
    roles_table = table('roles',
        column('role_id', String),
        column('role_name', String),
        column('description', String)
    )
    conn = op.get_bind()
    # Delete validator role if exists
    conn.execute(roles_table.delete().where(roles_table.c.role_id == 'validator'))
    # Insert roles if not present
    for rid, rname, desc in [
        ('admin', 'ADMIN', 'Admin role'),
        ('trainer', 'TRAINER', 'Trainer role'),
        ('user', 'USER', 'User role')
    ]:
        res = conn.execute(roles_table.select().where(roles_table.c.role_id == rid)).fetchone()
        if not res:
            conn.execute(roles_table.insert().values(role_id=rid, role_name=rname, description=desc))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'token_transactions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipe_versions', type_='foreignkey')
    op.drop_constraint(None, 'point_logs', type_='foreignkey')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'event_plans', type_='foreignkey')
    op.create_table('admin_action_logs',
    sa.Column('action_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], name=op.f('admin_action_logs_admin_id_fkey')),
    sa.PrimaryKeyConstraint('action_id', name=op.f('admin_action_logs_pkey'))
    )
    # ### end Alembic commands ###
