"""update database

Revision ID: 1b17080404b4
Revises: 
Create Date: 2025-12-31 16:48:23.038028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b17080404b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables only if they exist
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'admin_action_logs' in inspector.get_table_names():
        op.drop_table('admin_action_logs')
    if 'admin_profiles' in inspector.get_table_names():
        op.drop_table('admin_profiles')
    op.create_foreign_key(None, 'feedbacks', 'recipes', ['recipe_id'], ['recipe_id'])
    op.create_foreign_key(None, 'ingredients', 'recipe_versions', ['version_id'], ['version_id'])
    op.create_foreign_key(None, 'recipe_scores', 'recipes', ['recipe_id'], ['recipe_id'])
    op.create_foreign_key(None, 'steps', 'recipe_versions', ['version_id'], ['version_id'])
    op.create_foreign_key(None, 'token_transactions', 'recipes', ['recipe_id'], ['recipe_id'])
    # Add columns only if they do not exist
    user_columns = [col['name'] for col in inspector.get_columns('users')]
    if 'is_super_admin' not in user_columns:
        op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    if 'created_by' not in user_columns:
        op.add_column('users', sa.Column('created_by', sa.String(), nullable=True))
    if 'admin_action_type' not in user_columns:
        op.add_column('users', sa.Column('admin_action_type', sa.String(), nullable=True))
    if 'admin_action_target_type' not in user_columns:
        op.add_column('users', sa.Column('admin_action_target_type', sa.String(), nullable=True))
    if 'admin_action_target_id' not in user_columns:
        op.add_column('users', sa.Column('admin_action_target_id', sa.String(), nullable=True))
    if 'admin_action_description' not in user_columns:
        op.add_column('users', sa.Column('admin_action_description', sa.Text(), nullable=True))
    if 'admin_action_created_at' not in user_columns:
        op.add_column('users', sa.Column('admin_action_created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'validations', 'recipe_versions', ['version_id'], ['version_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validations', type_='foreignkey')
    op.drop_column('users', 'admin_action_created_at')
    op.drop_column('users', 'admin_action_description')
    op.drop_column('users', 'admin_action_target_id')
    op.drop_column('users', 'admin_action_target_type')
    op.drop_column('users', 'admin_action_type')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'is_super_admin')
    op.drop_constraint(None, 'token_transactions', type_='foreignkey')
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.drop_constraint(None, 'recipe_scores', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_table('admin_profiles',
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='admin_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('admin_id', name='admin_profiles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('admin_action_logs',
    sa.Column('action_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_profiles.admin_id'], name=op.f('admin_action_logs_admin_id_fkey')),
    sa.PrimaryKeyConstraint('action_id', name=op.f('admin_action_logs_pkey'))
    )
    # ### end Alembic commands ###
